language: python
dist: xenial

services:
  - redis-server

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=2.0
    - python: "2.7"
      env: DJANGO=2.1
    - python: "2.7"
      env: DJANGO=2.2

install:
  - pip install "Django>=$DJANGO,<${DJANGO}.99" django-redis

script:
  - "`which django-admin.py` test smart_session_engine.tests --settings=smart_session_engine.tests.settings --pythonpath=."
